p8105_hw3_yz4993
================
Yixin Zheng
2024-10-16

# Problem 1

This dataset contains 2595176 rows and 7 columns. Variables include
weather station id, date of observation, (tenths of mm), snowfall (mm),
snow depth (mm), and min and max temperature (tenths of degrees C).

Below we clean the data, creating separate variables for year, month,
and day and converting `tmax` and `tmin` to numeric. We find that 0 is
the most commonly observed value for snowfall. This is because most days
of the year, it does not snow at all in NY. The second most commonly
observed value is `NA`, indicating missingness. Other common values are
13, 25, and 51, suggesting that snowfall is originally recorded in
fractions of an inch and converted to mm.

``` r
ny_noaa %>% 
  count(snow) %>%
  arrange(desc(n))
```

    ## # A tibble: 282 × 2
    ##     snow       n
    ##    <int>   <int>
    ##  1     0 2008508
    ##  2    NA  381221
    ##  3    25   31022
    ##  4    13   23095
    ##  5    51   18274
    ##  6    76   10173
    ##  7     8    9962
    ##  8     5    9748
    ##  9    38    9197
    ## 10     3    8790
    ## # ℹ 272 more rows

``` r
ny_noaa = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin))
```

Below is a two-panel plot showing the average max temperature in January
and in July in each station across years. As expected, the mean
temperature in January is much lower than the mean temperature in July
for all stations and across all years. All stations appear to follow
similar trends of temperature peaks and valleys within a month across
the years, i.e. when one station has a high monthly mean temperature for
a given year, most other stations also have a high monthly mean
temperature for that year. We do see one uncharacteristically cold
station in July of 1987 or 1988, as well as a few other less drastic
outliers.

``` r
ny_noaa %>% 
  group_by(id, year, month) %>% 
  filter(month %in% c(1, 7)) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE, color = id)) %>% 
  ggplot(aes(x = year, y = mean_tmax, group = id)) + geom_point() + geom_path() +
  facet_grid(~month) +
  labs(title = "Mean monthly temperature for each station across years for January and July")
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

<img src="p8105_hw3_yz4993_files/figure-gfm/1.2 plot avg tmax-1.png" width="90%" />

Below we show a two-panel plot including (i) a hex plot of `tmax` vs
`tmin` for the full dataset; and (ii) a ridge plot showing the
distribution of snowfall values (in mm) greater than 0 and less than 100
separately by year.

From the hex plot we see that while there is some variability, the
majority of the data cluster tightly in the center of the distribution.
In relatively rare cases, it seems that `tmax` is less than `tmin`,
which raises questions about data recording and quality.

From the ridge plot, we see a multimodal density of snowfall within a
given year. Most stations see between 0 and 35 mm of snow in a year.
Then there is a another group of stations that see about 45 mm of snow,
and another group that sees nearly 80 mm. It is likely this
multimodality stems from the conversion of measurements in one system
(fractions of an inch) to another (using the metric system), which was
also noted in the table of common values.

``` r
hex = 
  ny_noaa %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()

ridge = 
  ny_noaa %>% 
  filter(snow < 100, snow > 0) %>%
  ggplot(aes(x = snow, y = as.factor(year))) + 
  geom_density_ridges()

hex + ridge
```

    ## Picking joint bandwidth of 3.76

<img src="p8105_hw3_yz4993_files/figure-gfm/1.3 plot tmax vs tmin and snowfall-1.png" width="90%" />
\# Problem 2

Below, the table shows the number of men and women across three
education categories: “Less than high school,” “High school equivalent,”
and “More than high school.” Both gender are roughly equally distributed
in the “Less than high school” and “More than high school” categories,
while in “High school equivalent” category there are more men than
women.

``` r
gender_education_table <- merged_data %>%
  group_by(sex, education) %>%
  summarize(count = n_distinct(seqn)) %>%
  pivot_wider(
    names_from = education,
    values_from = count,
    names_prefix = "Education: "
  ) %>%
  knitr::kable()
```

    ## `summarise()` has grouped output by 'sex'. You can override using the `.groups`
    ## argument.

``` r
gender_education_table
```

| sex | Education: Less than high school | Education: High school equivalent | Education: More than high school |
|:---|---:|---:|---:|
| Male | 28 | 36 | 56 |
| Female | 29 | 23 | 59 |

``` r
merged_data %>%
  filter(!is.na(education)) %>%
  ggplot(aes(x = age, fill = sex)) +
  geom_density(alpha = 0.5) +
  facet_grid(. ~ education) +
  scale_fill_manual(values = c("blue", "orange"), name = "Sex", labels = c("Male", "Female")) +
  labs(
    title = "Age Distribution by Education Category and Gender",
    x = "Age",
    y = "Density",
    caption = "Data from NHANES Study"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

<img src="p8105_hw3_yz4993_files/figure-gfm/2.2 reader-friendly table and visualization-1.png" width="90%" />
The age distribution plot below the table indicates that both male (in
blue) and female (in orange) follow a similar age pattern in the “More
than high school” category, with female peaking around age 30 (y-axis
represents density), and male peaking around 23-24. Both genders show a
decrease in density as age increases within this category. In the other
two categories, male and female exhibit different age patterns. In the
“Less than high school” category, male have the highest density around
ages 45-47, with the distribution being left-skewed. Despite a trough
around age 57, there are secondary peaks between ages 60-80. For female
in this category, the highest peak is around age 80, with the
distribution also being left-skewed, showing an increase in density as
age increases. In the “High school equivalent” category, female again
show a left-skewed distribution with a peak around age 80, while male
have a right-skewed distribution with a peak around age 21.

``` r
# aggregate across minutes to create a total activity variable for each participant
total_activity_data <- merged_data %>%
  group_by(seqn, sex, age, education) %>%
  summarize(total_activity = sum(activity, na.rm = TRUE)) %>%
  ungroup()
```

    ## `summarise()` has grouped output by 'seqn', 'sex', 'age'. You can override
    ## using the `.groups` argument.

``` r
total_activity_data %>%
  filter(!is.na(education)) %>%
  ggplot(aes(x = age, y = total_activity, color = sex)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "loess", se = FALSE) +
  facet_grid(. ~ education) +
  scale_color_manual(values = c("blue", "orange"), name = "Sex", labels = c("Male", "Female")) +
  labs(
    title = "Total Activity vs Age by Education Category and Gender",
    x = "Age",
    y = "Total Activity",
    caption = "Data from NHANES Study"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

    ## `geom_smooth()` using formula = 'y ~ x'

<img src="p8105_hw3_yz4993_files/figure-gfm/2.3 aggregate and plot-1.png" width="90%" />
The 3-panel plot above shows total daily activity plotted against age,
with separate panels for different education levels. Generally, activity
levels decrease with age across all education categories for both
genders, but there are notable exceptions. In both the “High school
equivalent” and “More than high school” categories, females exhibit
slightly higher activity levels compared to males. In the “Less than
high school” category, females have higher activity levels than males
before age 50, but lower levels after age 50. Additionally, in the “High
school equivalent” category, females show significantly higher activity
levels than males around age 40.

``` r
# convert minute to hours
activity_timecourse_data <- merged_data %>%
  mutate(hour = minute / 60) %>%  # 
  group_by(hour, education, sex) %>%
  summarize(avg_activity = mean(activity, na.rm = TRUE)) %>%
  ungroup()
```

    ## `summarise()` has grouped output by 'hour', 'education'. You can override using
    ## the `.groups` argument.

``` r
activity_timecourse_data %>%
  filter(!is.na(education)) %>%
  ggplot(aes(x = hour, y = avg_activity, color = sex)) +
  geom_line() +  # Add the activity line
  geom_smooth(method = "loess", se = FALSE) +  # smooth trend lines
  facet_grid(. ~ education) +  #  by education
  scale_color_manual(values = c("blue", "orange"), name = "Sex", labels = c("Male", "Female")) +
  labs(
    title = "24-Hour Activity Time Course by Education Level and Sex with Smooth Trends",
    x = "Hour of the Day",
    y = "Average Activity",
    caption = "Data from NHANES Study"
  ) +
  scale_x_continuous(breaks = seq(0, 24, by = 2), labels = seq(0, 24, by = 2)) +  # set x-axis breaks at every 2 hours
  theme_minimal() +
  theme(legend.position = "bottom")
```

    ## `geom_smooth()` using formula = 'y ~ x'

<img src="p8105_hw3_yz4993_files/figure-gfm/2.4 3-panel plot-1.png" width="90%" />
The plot above also reflects similar observations to the previous one,
with males and females having comparable average activity levels by the
hour in the “Less than high school” category, while females exhibit
noticeble higher average activity levels than males in the other two
categories. It is notable that, across all education levels, both men
and women follow similar hourly activity patterns—activity slowly
increase from 00:00 to 10:00, peaks around 10:00- 13:00, then a steady
decline after.

# Problem 3

describe the resulting dataset.

``` r
jan_2020 <- read_csv("~/Desktop/Data Science/HW/HW3/p8105_hw3_yz4993/data/Jan 2020 Citi.csv") %>%
  clean_names() %>%
  mutate(year = 2020, month = "January")
```

    ## Rows: 12420 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
jan_2024 <- read_csv("~/Desktop/Data Science/HW/HW3/p8105_hw3_yz4993/data/Jan 2024 Citi.csv") %>%
  clean_names() %>%
  mutate(year = 2024, month = "January")
```

    ## Rows: 18861 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
july_2020 <- read_csv("~/Desktop/Data Science/HW/HW3/p8105_hw3_yz4993/data/July 2020 Citi.csv") %>%
  clean_names() %>%
  mutate(year = 2020, month = "July")
```

    ## Rows: 21048 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
july_2024 <- read_csv("~/Desktop/Data Science/HW/HW3/p8105_hw3_yz4993/data/July 2024 Citi.csv") %>%
  clean_names() %>%
  mutate(year = 2024, month = "July")
```

    ## Rows: 47156 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
citi_bike <- bind_rows(jan_2020, jan_2024, july_2020, july_2024)

# tidy
citi_bike <- citi_bike %>%
  # convert weekdays to a factor with appropriate levels
  mutate(
    weekdays = factor(weekdays, 
                      levels = c("Monday", "Tuesday", "Wednesday", "Thursday", 
                                 "Friday", "Saturday", "Sunday"), 
                      ordered = TRUE),
    
    # Optionally, we could convert weekdays to numeric (Monday = 1, ..., Sunday = 7)
    # weekdays = as.numeric(weekdays),
    
    # rename and simplify rideable_type to bike_type
    bike_type = recode(rideable_type, 
                       "classic_bike" = "classic", 
                       "electric_bike" = "electric"),
    
    # rename and encode member_casual to member_status as a factor
    member_status = factor(member_casual, 
                           levels = c("member", "casual"), 
                           labels = c("Member", "Casual")),
    
    # optionally,  we could convert month to a numeric value (January = 1, ..., December = 12)
    # month_num = match(month, month.name),
    
    # month as a factor for categorical use
    month = factor(month, 
                   levels = month.name),
    
    # year is numeric
    year = as.numeric(year),
    
    # duration is numeric
    duration = as.numeric(duration)
  ) %>%
  #remove the old columns (member_casual and rideable_type)
  select(-member_casual, -rideable_type)

str(citi_bike)
```

    ## tibble [99,485 × 9] (S3: tbl_df/tbl/data.frame)
    ##  $ ride_id           : chr [1:99485] "4BE06CB33B037044" "26886E034974493B" "24DC56060EBE6260" "EEDC1053582D02E5" ...
    ##  $ weekdays          : Ord.factor w/ 7 levels "Monday"<"Tuesday"<..: 2 3 5 7 5 7 7 7 4 2 ...
    ##  $ duration          : num [1:99485] 15.33 5.31 9.69 7 2.85 ...
    ##  $ start_station_name: chr [1:99485] "Columbus Ave & W 95 St" "2 Ave & E 96 St" "Columbia St & Rivington St" "W 84 St & Columbus Ave" ...
    ##  $ end_station_name  : chr [1:99485] "E 53 St & Madison Ave" "1 Ave & E 110 St" "Grand St & Elizabeth St" "Columbus Ave & W 72 St" ...
    ##  $ year              : num [1:99485] 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 ...
    ##  $ month             : Factor w/ 12 levels "January","February",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ bike_type         : chr [1:99485] "classic" "classic" "classic" "classic" ...
    ##  $ member_status     : Factor w/ 2 levels "Member","Casual": 1 1 1 1 1 1 1 1 1 1 ...

From the code output above, we could see this merged dataset `citi_bike`
contains 99485 rows and 9 columns. The dataset represents bike rides 1%
of all rides taken on the NYC Citi Bike system with a total duration
less than 4 hours in each of four months (2020 and 2024 Jan and July).
It includes details such as ride ID, weekdays, ride duration, start and
end station names, year, month, bike type, and member status. we have
cleaned and tidied the data: `weekdays` were encoded as an ordered
factor, from Monday to Sunday. `rideable type` was renamed to
`bike_type` and simplified to `classic` or `electric.`
`membership status` was renamed from `member_casual` to `member_status`
and encoded as a factor with levels “Member” and “Casual.” `month` was
encoded as a factor for categorical purpose.

``` r
rides_by_yrmth <- citi_bike %>%
  group_by(year, month, member_status) %>%
  summarize(total_rides = n(), .groups = "drop") %>%
  pivot_wider(names_from = member_status, values_from = total_rides, values_fill = 0)

knitr::kable(rides_by_yrmth, caption = "Total Number of Rides by Year, Month, and Member Status")
```

| year | month   | Member | Casual |
|-----:|:--------|-------:|-------:|
| 2020 | January |  11436 |    984 |
| 2020 | July    |  15411 |   5637 |
| 2024 | January |  16753 |   2108 |
| 2024 | July    |  36262 |  10894 |

Total Number of Rides by Year, Month, and Member Status

From the table above, we observe that the number of Citi Bike members
increased consistently over time, with a increa jump between January and
July in 2024. For casual riders, while there is a notable dip in January
2024 compared to the previous July 2020, the overall trend still shows
growth. This suggests that both membership and casual usage have
generally increased over time, with fluctuations maybe influenced by
season changes.

``` r
popular_stations <- citi_bike %>%
  filter(year == 2024, month == "July") %>%
  group_by(start_station_name) %>%
  summarize(total_rides = n()) %>%
  arrange(desc(total_rides)) %>%
  top_n(5, wt = total_rides)

knitr::kable(popular_stations, caption = "Top 5 Starting Stations in July 2024 by Number of Rides")
```

| start_station_name       | total_rides |
|:-------------------------|------------:|
| Pier 61 at Chelsea Piers |         163 |
| University Pl & E 14 St  |         155 |
| W 21 St & 6 Ave          |         152 |
| West St & Chambers St    |         150 |
| W 31 St & 7 Ave          |         146 |

Top 5 Starting Stations in July 2024 by Number of Rides

From the table above, we observe that the number of rides among the top
5 starting stations in July 2024 is pretty close, with Pier 61 at
Chelsea Piers having the highest number of rides at 163, and W 31 St & 7
Ave have the lowest – 146 rides.

``` r
effect_median_ride <- citi_bike %>%
  group_by(year, month, weekdays) %>%
  summarize(median_duration = median(duration, na.rm = TRUE), .groups = "drop")

ggplot(effect_median_ride, aes(x = weekdays, y = median_duration, color = month)) + 
  geom_line(aes(group = interaction(year, month)), size = 1) + 
  facet_wrap(~ year) +
  labs(
    title = "Effects of Day of the Week, Month, and Year on Median Ride Duration",
    x = "Day of the Week",
    y = "Median Ride Duration (minutes)",
    color = "Month"
  ) + 
  theme_minimal() + 
  theme(legend.position = "bottom") +
  scale_color_viridis_d()
```

<img src="p8105_hw3_yz4993_files/figure-gfm/3.4 plot effects of time on median ride duration-1.png" width="90%" />

Both panels show that ride duration follows a similar weekly pattern,
with durations increasing significantly starting from the weekend,
suggesting higher traffic during weekends. In both 2020 and 2024, we
observe that median ride duration is higher in July compared to January,
with a more significant difference in 2020 (July vs January). This
difference between months suggests a seasonal pattern, while the overall
decrease in ride duration from 2020 to 2024 could indicate that more
transportation options (like public transportation or electric bikes)
have become available as time goes by, reducing the need for longer
rides.

There were relatively few electric Citi Bikes in 2020, but many more are
available now. For data in 2024, make a figure that shows the impact of
month, membership status, and bike type on the distribution of ride
duration. Comment on your results.

``` r
citi_bike_2024 <- citi_bike %>%
  filter(year == 2024)

ggplot(citi_bike_2024, aes(x = duration, fill = bike_type)) +
  geom_density(alpha = 0.6) +
  facet_grid(month ~ member_status) +
  scale_fill_viridis_d(name = "Bike Type") +
  labs(
    title = "Impact of Month, Membership Status, and Bike Type on Distribution of Ride Duration (2024)",
    x = "Ride Duration (minutes)",
    y = "Density",
    caption = "Data from NYC Citi Bike (2024)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  xlim(0, 80)  # set x-axis limits from 0 to 80 for better observe
```

<img src="p8105_hw3_yz4993_files/figure-gfm/3.5 figure of impact-1.png" width="90%" />

This plot shows how ride duration distributions vary by month,
membership status, and bike type for the year 2024. In all panels, we
see that the density curves peak between 0 and 20 minutes, indicating
that most rides, regardless of bike type or membership status, are quite
short. Electric bikes (yellow) generally show a higher density at
shorter ride durations, especially among casual riders. Notably, in July
2024, among members, classic bikes(purple) surpass electric bikes in
usage. Casual riders also tend to have a broader range of ride durations
compared to members. Additionally, ride durations in July tend to be
longer than those in January, suggesting some seasonal variation in ride
patterns.
